#ifndef CST_DISPLAY_H
#define CST_DISPLAY_H

#define FULL_BLOCK "██"
#define THREE_QUART_BLOCK "▓▓"
#define HALF_BLOCK "▒▒"
#define QUART_BLOCK "░░"
#define VERT_WALL_LEFT "║ "
#define VERT_WALL_RIGHT " ║"
#define HORI_WALL "══"
#define TOP_LEFT_CORNER " ╔"
#define TOP_RIGHT_CORNER "╗ "
#define BOTTOM_LEFT_CORNER " ╚"
#define BOTTOM_RIGHT_CORNER "╝ "
#define RIGHT_JUNCTION " ╠"
#define LEFT_JUNCTION "╣ "
#define UP_RIGHT_JUNCTION "═╩"
#define UP_LEFT_JUNCTION "╩═"
#define DOWN_LEFT_JUNCTION "╦═"
#define DOWN_RIGHT_JUNCTION "═╦"
#define LEFT_CROSS_JUNCTION "╬═"
#define RIGHT_CROSS_JUNCTION "═╬"

#define BLACK "\033[0;30m"
#define RED "\033[0;31m"
#define GREEN "\033[0;32m"
#define YELLOW "\033[0;33m"
#define BLUE "\033[0;34m"
#define MAGENTA "\033[0;35m"
#define CYAN "\033[0;36m"
#define WHITE "\033[0;37m"
#define BRIGHT_BLACK "\033[0;90m"
#define BRIGHT_RED "\033[0;91m"
#define BRIGHT_GREEN "\033[0;92m"
#define BRIGHT_YELLOW "\033[0;93m"
#define BRIGHT_BLUE "\033[0;94m"
#define BRIGHT_MAGENTA "\033[0;95m"
#define BRIGHT_CYAN "\033[0;96m"
#define BRIGHT_WHITE "\033[0;97m"

#endif
