#ifndef SAVE_FILE_CST_H
#define SAVE_FILE_CST_H

#define SAVE_INDEX_ENEMIES_DEAD 0

#define SAVE_INDEX_PLAYER_X 1
#define SAVE_INDEX_PLAYER_Y 2

#define SAVE_INDEX_PLAYER_HEALTH 3
#define SAVE_INDEX_PLAYER_MAX_HEALTH 4

#define SAVE_INDEX_PLAYER_STAMINA 5
#define SAVE_INDEX_PLAYER_MAX_STAMINA 6

#define SAVE_INDEX_PLAYER_EXP 7
#define SAVE_INDEX_PLAYER_EXP_NEXT_LEVEL 8
#define SAVE_INDEX_PLAYER_LEVEL 9

#define SAVE_INDEX_PLAYER_CHARGED 10
#define SAVE_INDEX_PLAYER_AIM 11

#define SAVE_INDEX_PLAYER_ATTACK 12

#endif
